- name: Install required packages
  apt:
    name: [apt-transport-https,ca-certificates,curl,gnupg-agent,software-properties-common,libffi-dev,libssl-dev]


- name:  Add Docker’s official GPG key
  apt_key:
    url:  https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88

- name: Add repository 
  apt_repository:
    filename: docker
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable

- name: Install Docker
  apt:
    name: [docker-ce,docker-ce-cli,containerd.io] 
