   
# CMAK is a tool for managing Apache Kafka clusters
# repository: https://github.com/yahoo/CMAK
# image: https://hub.docker.com/r/hlebalbau/kafka-manager

version: '3.6'
services:
  kafka_manager:
    build: .
    image: cmak
    container_name: "{{docker_appname}}"
    restart: always
    ports:
      - "{{docker_apps_cmak_port}}:9000"
    environment:
      ZK_HOSTS: "{{docker_gateway.stdout}}:2181"
      APPLICATION_SECRET: "random-secret"
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: 123456

      
    
networks:
  default:
    external:
      name: "{{docker_addnetwork}}"